using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("CruiseControl.NET")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003 - 2014 ThoughtWorks Inc.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("Git hash : 0000000000000000000000000000000000000000")]

